typography_spectrum: 0.7070917601231486
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.6047856933437288
  lightness: 0.41587243019603193
  saturation: 0.1769517003558576
  rhythmicContrast: 0.3591753977816552
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.02184305270202458
analytics:
  google: null
  facebook: null
  twitter: null
name: Micaela Brown
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Instagram
    url: instagram.com/micaela_brown
    type: external
favicon: null
title: Micaela Brown
description: experience creator
purpose: []
