typography_spectrum: 0.5944342988077551
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6171656721271574
  lightness: 0.5039352208841592
  saturation: 0.8746031266637146
  rhythmicContrast: 0.9605046899523586
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7253765151835978
analytics:
  google: null
  facebook: null
  twitter: null
name: Micaela Brown
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Instagram
    url: instagram.com/micaela_brown
    type: external
favicon: null
title: Entrepreneur
description: experience creator
purpose: []
